# Generated by Django 5.1.7 on 2025-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0002_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='static/photos/default.jpg', upload_to='static/img/photos/'),
        ),
    ]
