# Generated by Django 5.1.7 on 2025-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0003_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains')], default='Vegetables', max_length=20),
        ),
    ]
