# Generated by Django 5.1.7 on 2025-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='Farm2Home/static/photos/default.jpg', upload_to='Farm2Home/static/img/photos/'),
        ),
    ]
