# Generated by Django 5.1.7 on 2025-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0005_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='static/photos/default.jpg', upload_to='static/img/photos/'),
        ),
    ]
