# Generated by Django 5.1.7 on 2025-03-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0007_tradingprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingprofile',
            old_name='account_no',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='tradingprofile',
            old_name='trading_name',
            new_name='tradingName',
        ),
    ]
