# Generated by Django 5.1.7 on 2025-03-18 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0008_rename_account_no_tradingprofile_accountnumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='productCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='productDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='productPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='freshHarvested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='naturalFarming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='organicCertified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pesticidefree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pricePerUnit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('500g', '500g'), ('Dozen', 'Dozen'), ('Bundle', 'Bundle')], default='Kg', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='productDiscount_inpercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(null=True, upload_to='static/img/photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='returnPolicy_inHours',
            field=models.CharField(choices=[('7days', '168'), ('3days', '72'), ('1day', '24'), ('nonreturnable', '0')], default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='product',
            name='stockQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
