# Generated by Django 4.2.20 on 2025-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm2Home', '0014_sellerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='returnPolicy_inHours',
            field=models.CharField(choices=[('7days', '168'), ('3days', '72'), ('1day', '24'), ('nonreturnable', '0')], default='0', max_length=13),
        ),
    ]
